
               <h3><span id="ContentPlaceHolder1_lbl_title">Mortgage Newsletter</span></h3>
              
                  <p id="ContentPlaceHolder1_span_aboutus"></p><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td valign="middle" align="left" style="background-color: rgb(225, 225, 225); font-family: Arial,Helvetica,sans-serif; font-size: 18px; color: rgb(102, 102, 102); border-bottom: 1px solid rgb(238, 28, 35);"><strong>Guaranteed Rate Report</strong></td>
            <td valign="middle" align="right" style="background-color: rgb(225, 225, 225); border-top: 0px solid rgb(51, 51, 51); border-bottom: 1px solid rgb(238, 28, 35);"><a target="_self" href="http://www.guaranteedrate.com"><img height="27" width="101" border="0" align="right" title="Guaranteed Rate" src="http://www.guaranteedrate.com/images/header_logo.png" alt="Guaranteed Rate"></a></td>
        </tr>
    </tbody>
</table>
<p><span style="line-height: 110%; font-family: arial; color: rgb(161, 15, 21); font-size: 20px; font-weight: bold;"><span style="font-size: medium;">The Debt Ceiling, Economic Stimulus, &amp; the Impact on Rates</span></span></p>
<p style="font-size: 12px;">As  we closed last week, the stock market  had posted weekly declines for  the last 6 weeks straight, which means  that mortgage rates continue to  be very strong. Last week alone, stocks  fell 2.2%, and without any real  positive counteracting data, concerns  continued to rise over economic  weakness going forward. Credit fears  continue in Europe with concern in  Portugal, Spain, Greece, Ireland,  etc. With the shape of the yield curve  and an outlook for low  short-term rates, adjustable rate mortgage  products also continue to  look strong, with much lower rates than fixed  rate products. A couple  of Fed members did speak last week that weak  jobs data hasn’t changed  their view on monetary policy, or the economy  going forward. That being  said, speculation is rising that some sort of  stimulus may be needed  to help the U.S. economy along the path to  recovery. Any talk of  stimulus, however, will be accompanied with talks  of government  spending and the debt ce iling, which will become a hotter  topic until  as we near the August deadline. If investors start selling  Treasuries  because of the debt ceiling uncertainty, or rating agencies  downgrade  U.S. debt, this should drive interest rates higher. There  wasn’t much  economic data released this morning, so attention seems to  be on  Federal Reserve speeches, presidential debates, and news abroad.   Economic news data does pick up later this week, however, producer and   consumer price numbers to indicate inflation levels, retail sales   figures, and manufacturing numbers, just to name a few. There is a   definite possibility that mortgage rates continue to jump around.</p>
<p class="MsoNormal">A  couple of Fed members did speak last week that  weak jobs data hasn’t  changed their view on monetary policy, or the  economy going forward.&nbsp;  That being said, speculation is rising that  some sort of stimulus may be  needed to help the U.S. economy along the  path to recovery.&nbsp; Any talk  of stimulus, however, will be accompanied  with talks of government  spending and the debt ceiling, which will  become a hotter topic until as  we near the August deadline.&nbsp; If  investors start selling Treasuries  because of the debt ceiling  uncertainty, or rating agencies downgrade  U.S. debt, this should drive  interest rates higher.</p>
<p class="MsoNormal">There  wasn’t much economic data released this  morning, so attention seems to  be on Federal Reserve speeches,  presidential debates, and news abroad.&nbsp;  Economic news data does pick up  later this week, however, producer and  consumer price numbers to  indicate inflation levels, retail sales  figures, and manufacturing  numbers, just to name a few.&nbsp; There is a  definite possibility that  mortgage rates continue to jump around.&nbsp;</p>
<p>&nbsp;</p>
<p style="font-size: 12px;"><img height="212" width="500" src="http://www.guaranteedrate.com/images/email/GuaranteedRate-Rates.jpg" alt=""></p>
<p style="font-size: 12px;"><img height="226" width="500" style="border: 1px solid black;" src="http://www.guaranteedrate.com/images/email/GuaranteedRate-Arrows.jpg" alt=""></p>
       
               
